#! /usr/bin/bash
############
# crswap
#
# Syntax  : # crswap <swapfile>
# Purpose : Active the given file as a swapfile.
#     crswap checks some parameters before it 
#     actually activates the swapfile.
#
#
# (c) 2016 PeterVG
# Version	ChangeDate`	Author		Changes
# 201611A	17-11-2016	PeterVG		Mist-Of-Time


# Check if a swapfile is given as parameter
if [[ $# -ne 1 ]] ; then
	echo "Error : No swapspace given" >&2
	exit 2
fi

# Check if given swapspace exists
if [[ ! -e $1 ]] ; then
	echo "Error : Given swapspace not found ($1)" >&2
	exit 2
fi

# Check if command is run as root
user=$( id -un )
if [[ ! $user = "root" ]] ; then
	echo "Error : $(basename $0) should be run as root" >&2
	exit 2
fi

# Check if given swapspace is owned by root:root
owner=$( ls -l $1 | awk '{print $3}' )
group=$( ls -l $1 | awk '{print $4}' )
if [[ ! $owner = "root" ]] ; then
	echo "Error : Given swapspace is not owned by root" >&2
	exit 2
fi

if [[ ! $group = "root" ]] ; then
	echo "Error : Given swapspace is not owned by group" >&2
	exit 2
fi


# Check if given swapspace has mode 600
mode=$( stat -c "%a" $1 )
if [[ ! $mode = 600 ]] ; then
	echo "Error : Given swapspace has incorrect mode ($mode)" >&2
	exit 2
fi


# When we get here we can activate the swapspace. 
(
	mkswap $1 || echo "Error : mkswap command encountered errors" >&2
	swapon $1 || echo "Error : swapon command encountered errors" >&2
) >/dev/null 2>&1


# Inform user that swapspace is activated
swapon -s

# eos
